services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: profinfly_ai

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - profinfly-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile 

    container_name: profinfly-backend

    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres

    networks:
      - profinfly-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend

    container_name: profinfly-frontend

    restart: unless-stopped

    ports:
      - "3000:80"

    depends_on:
      - backend

    networks:
      - profinfly-network

volumes:
  postgres-data:

networks:
  profinfly-network:

